### ISSUE TITLE
viewer: tag propositions do not take the subtraction operator into account

### ISSUE THREAD

**Issue by zeroinformatique** [ldgallery/ldgallery#220] opened 2020-05-16 15:37 UTC
Add a tag, then substract another tag, the proposition list offers both tags instead of only the first one minus the second one.

**Comment by pacien** [comment] 2023-02-20 19:01
Minimum Reproducible Example in the branch `mre_only_subtraction_shows_others`.

**Comment by pacien** [comment] 2023-02-20 19:15
Could not reproduce in ldgallery v2.2. This might have been solved in a previous version. Closing.

**Closed by pacien** 2023-02-20 19:15 UTC
Labels: class:bug, component:viewer
